# mypy.ini

[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True

# This automatically excludes site-packages, venv, etc.
exclude = ["venv/", ".venv/", "env/", ".env/"]

# Only check your own modules strictly
# [mypy.your_own_package.*]
# disallow_untyped_defs = True
# disallow_incomplete_defs = True
