name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["lint"]  # Name of the lint workflow
    types:
      - completed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Install Heroku CLI
        run: |
          heroku login
          heroku container:login
      - name: Build and push Docker image to Heroku
        run: |
          docker build -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web .
          heroku container:push -a ${{ env.HEROKU_APP_NAME }} web
      - name: Release Heroku app
        run: |
          heroku container:release -a ${{ env.HEROKU_APP_NAME }} web
